  web:
    build: .
    image: "${DOCKER_REPO}/${DOCKER_WEB_IMAGE}"
    command: /code/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: postgres
